### ISSUE TITLE
encrypt from <object> to File  decrypt file to <object>

### ISSUE THREAD

**Issue by godfather667** [mdp/gibberish#13]
I am creating a password storage program and editor.  I do not want
the plain text data to ever be written to disk.  I want to decrypt the
file directly to an array of strings and write back a array of stings 
encrypted to disk.  

There may be a way to do this by I have been beating my head into a wall
for 12 hours.   

I can read a encrypted file into stringIO Object and convert it with stringIO.string
but cannot reverse this process.  Trying to encrypt_stream("stringIO object", fd)
always crashes on flush in AES.rb

I suspect I am stupid in some respect -- admin@hawthorne-press.com

**Comment by mdp** [comment]
Sorry, I missed this bug report when it came in. I'm not sure the best way to go about getting this done unfortunately.
