### ISSUE TITLE
OpenSSL interop not valid

### ISSUE THREAD

**Issue by assafshomer** [mdp/gibberish#17]
Pasting this into my linux Mint box command line:

echo "U2FsdGVkX1/D7z2azGmmQELbMNJV/n9T/9j2iBPy2AM=\n" | openssl enc -d -aes-256-cbc -a -k p4ssw0rd

gives an error:

error reading input file

**Comment by mdp** [comment]
OpenSSL broke the compatibility with older version of OpenSSL. Gibberish 2.0 and beyond will stick with just using SJCL compatible encryption.
