### ISSUE TITLE
Consider adding warning about openssl usage

### ISSUE THREAD

**Issue by kevgrig** [mdp/gibberish#18]
Quoting from a [similar issue with forge.js](https://github.com/digitalbazaar/forge/issues/209):

> In the [README](https://github.com/digitalbazaar/forge/blob/ffcd2db4f3c8547407fd35d92db9b272a8b971f1/README.md#cipher), there is an example called, "Using forge in node.js to match openssl's "enc" command line tool." There is [an answer on StackExchange Information Security that says](http://security.stackexchange.com/a/29139), in part:
> 
> > The encryption format used by OpenSSL is non-standard: it is "what OpenSSL does", and if all versions of OpenSSL tend to agree with each other, there is still no reference document which describes this format except OpenSSL source code...
> > 
> > The process by which the password and salt are turned into the key and IV is not documented, but a look at the source code shows that it calls the OpenSSL-specific EVP_BytesToKey() function, which uses a custom key derivation function with some repeated hashing. This is a non-standard and not-well vetted construct (!)... **the "iteration count" is set by the enc command to 1 and cannot be changed (!!!!)**. This means that the first 16 bytes of the key will be equal to MD5(password||salt), and that's it.
> > 
> > **This is quite weak ! Anybody who knows how to write code on a PC can try to crack such a scheme and will be able to "try" several dozens of millions of potential passwords per second** (hundreds of millions will be achievable with a GPU). If you use "openssl enc", make sure your password has very high entropy ! (i.e. higher than usually recommended; aim for 80 bits, at least). Or, preferably, don't use it at all; instead, go for something more robust (**GnuPG, when doing symmetric encryption for a password, uses a stronger KDF with many iterations of the underlying hash function**).
> 
> I've put a few concerning parts in **bold**. Do you have any opinions on this? Do you think an example that writes a gpg-format file would be better?

...

> We should probably add similar warning(s) to the README. People (unfortunately) use that tool so we need to have the example available, but a warning is a good idea. More examples (eg: gpg-format) are also welcome.

And [the fix](https://github.com/digitalbazaar/forge/issues/209) to forge's README:

> (**Note**: OpenSSL "enc" uses a non-standard file format with a custom key derivation function and a fixed iteration count of 1, which some consider less secure than alternatives such as [OpenPGP](https://tools.ietf.org/html/rfc4880)/[GnuPG](https://www.gnupg.org/))

**Comment by mdp** [comment]
Moved 2.0.0 to SJCL compatible AES which includes password hardening.
