### ISSUE TITLE
TypeError (Cannot visit Gibberish::AES::SJCL::Plaintext)

### ISSUE THREAD

**Issue by cmwright** [mdp/gibberish#20]
Here's what I'm doing in the code: 
```
cipher = Gibberish::AES.new(key)
cipher.decrypt(encrypted_string)
```

Inside of a rails controller, when I try to use the `decrypt` method I get this error `TypeError (Cannot visit Gibberish::AES::SJCL::Plaintext)`. I've played around with the file a bit, and I can get rid of the error by just returning the `out` variable instead of initializing the `Plaintext` object. This will obviously break any authenticated data so not a long term solution, but I was wondering if you've ever seen this error and if there is an easy fix for it? 

For what it's worth Gibberish generally works perfectly well while using it from the rails console, there's just something weird happening when inside of a request.

**Comment by mdp** [comment]
Really interesting. Can you give me a couple pieces of info?

- Rails version
- Ruby version

I'll take a look at it tonight. Thanks

**Comment by cmwright** [comment]
Thanks for your help!

I am running:
ruby: `ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]`
rails: `Rails 3.2.21`

**Comment by mdp** [comment]
So something like this in a Rails controller under 3.2.21

```ruby
  def index
    key = "crazylongkey"
    cipher = Gibberish::AES.new(key)
    encrypted_string = cipher.encrypt('supersecret')
    render text: "#{encrypted_string} -> #{cipher.decrypt(encrypted_string)}"
  end
```

I'm trying to replicate the error, but this example works. Could you give me a bit more detail on the code you're running?

Thanks

**Comment by mdp** [comment]
@cmwright Any more information on this? I wasn't able to track it down on my own fresh rails install.

**Comment by cmwright** [comment]
@mdp I tried to go through the steps reproducing this in a fresh proect, saw the same thing you did. The only thing I can think of is that the project I was seeing the error in had some sort of gem conflict, unfortunately the project has an immense amount of gems installed so tracking that down is going to be pretty tricky

**Comment by cmwright** [comment]
will close as it doesn't seem to be generally be an Gibberish issue
