### ISSUE TITLE
Bumping to v2:  Terribly slow

### ISSUE THREAD

**Issue by findchris** [mdp/gibberish#22]
Only after bumping to v2.0 and deploying, and we saw huge latency spikes and CPU consumption, did we note this part of the README:  `100,000 iterations of PBKDF2 password hardening`

Our bad, no doubt.

I'm just noting here that you should call out just how slow this makes your code:

```ruby
cipher = Gibberish::AES.new('p4ssw0rd')
Benchmark.bmbm do |x|
  x.report('encrypt'){ 1_000.times{cipher.encrypt("some secret text")}}
end

=> 
              user     system      total        real
encrypt 197.830000   0.000000 197.830000 (197.830117)
```

That's 200ms per simple encryption.  Useful in some cases, but I think it deserves an explicit warning for those of us using gibberish in web applications.

**Comment by mdp** [comment]
I'll update the docs on this. Right now it defaults to a very high number of iterations to harden the password, but it's customizable.

`cipher = Gibberish::AES.new('p4ssw0rd', {iter:1000});`

Find a balance between security and speed by adjusting the number of iterations.

**Comment by findchris** [comment]
:+1:

**Comment by findchris** [comment]
```
 > cipher = Gibberish::AES.new('p4ssw0rd', {iter:1000});
RuntimeError: unsupported cipher algorithm (aes-{:iter=>1000}-cbc)
```

**Comment by mdp** [comment]
Make sure this is 2.0 of Gibberish and now the old 1.x version. The method signature is now `initialize(password, size, mode)` whereas 2.x is `initialize(password,options)` which makes me think that error is the old version trying to make `{iter:1000}` into the size param, where it would normally be "aes-256-cbc"

**Comment by findchris** [comment]
I'm sorry:  I had my version locked.  Thanks.
