### ISSUE TITLE
NotImplementedError: pbkdf2_hmac() function is unimplemented on this machine

### ISSUE THREAD

**Issue by sselvamani22** [mdp/gibberish#23]
I am getting an error when I try to encrypt the data on heroku. On my local it is working fine. But only problem with heroku. Here the log which I got when I encrypt the data.

    cipher = Gibberish::AES.new('p4ssw0rd')
    cipher.encrypt("My Secure data")
    NotImplementedError: pbkdf2_hmac() function is unimplemented on this machine
	from /app/vendor/bundle/ruby/2.2.0/gems/gibberish-2.0.0/lib/gibberish/aes.rb:140:in `pbkdf2_hmac'
	from /app/vendor/bundle/ruby/2.2.0/gems/gibberish-2.0.0/lib/gibberish/aes.rb:140:in `encrypt'
	from /app/vendor/bundle/ruby/2.2.0/gems/gibberish-2.0.0/lib/gibberish/aes.rb:100:in `encrypt'

**Comment by mdp** [comment]
This might be an issue with that particular ruby version. Looking at Heroku, they list support for 2.2.2 now, and it's working for me in that version. From your logs it looks like you're on 2.2.0.

I've tried 2.0.0 and 2.2.2 on Heroku and both work. Is it possible to try updating to the latest and see if that fixes it?

**Comment by sselvamani22** [comment]
In my heroku I have two app with ruby 2.2.0 and rails 4.2.0. One of the app works fine but not another.
My first app OpenSSL version is "OpenSSL 0.9.8k 25 Mar 2009", and second app version is "OpenSSL 1.0.1f 6 Jan 2014". My second app works fine, but first app is not working.

**Comment by mdp** [comment]
Gibberish requires OpenSSL >=1.01. I'll add this to the docs.
