### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Skeyelab** [mdp/gibberish#24]
I'm using gibberish by way of mongoid-encrypted-fields.  I'm getting the following error when I run this locally.  This works fine when I deploy the app to heroku and connect to a console

`Loading development environment (Rails 4.2.6)
[1] pry(main)> u = Testuser.first
MONGODB | Adding localhost:27017 to the cluster.
MONGODB | localhost:27017 | rails_desk_development.find | STARTED | {"find"=>"testusers", "filter"=>{}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | rails_desk_development.find | SUCCEEDED | 0.000979s
=> #<Testuser _id: 5705206249c65a7aa8397a78, email: "eric@asdf.com", encrypted_field: nil>
[2] pry(main)> u.encrypted_field = "blhas"
TypeError: no implicit conversion of nil into String
from /Users/edahl/.rvm/gems/ruby-2.3.0@deskulator/gems/gibberish-2.0.0/lib/gibberish/aes.rb:140:in `pbkdf2_hmac'
[3] pry(main)>`

**Comment by mdp** [comment]
This is probably an issue with a very old version of OpenSSL on your local machine. Gibberish requires OpenSSL >= 1.0.1
