### ISSUE TITLE
Encrypt with openSSL CLI, decrypt with Gibberish

### ISSUE THREAD

**Issue by KidA001** [mdp/gibberish#29]
I have a client that is using the openSSL CLI to encrypt data, and sending it to us to decrypt in our ruby application. Below you gave an example of the inverse scenario...is it possible to give an example of the scenario above? I have been unable to decrypt data from them in `aes-256-cbc` when they pass me the IV, Salt, Key. I have the passphrase in my environment. I've tried decrypting it with ruby's openSSL library and with your gibberish gem, but no success.

**Your Example**
```
AES-256-CBC mode

cipher = Gibberish::AES::CBC.new('p4ssw0rd')
cipher_text = cipher.encrypt("some secret text")
# => U2FsdGVkX1/D7z2azGmmQELbMNJV/n9T/9j2iBPy2AM=

cipher.decrypt(cipher_text)

# From the command line
echo "U2FsdGVkX1/D7z2azGmmQELbMNJV/n9T/9j2iBPy2AM=\n" | openssl enc -d -aes-256-cbc -a -k p4ssw0rd
```

This is what they are doing in the CLI and I would like to decrypt with Gibberish:
```
echo 'someTextIWantToEncrypt' | openssl enc -aes-256-cbc -base64 -p -e -pass pass:supersecretpassword

# output
salt=40D451D7BE939D10
key=6980F239A37820A7BD5CC78D60BFED154693D72A762183D7DE397FD6AADCE665
iv =375B750D73BDAC4EAE94B9D00F000937
U2FsdGVkX19A1FHXvpOdEPZ0o2iPFcQLICGry9EpxgpUbnuRhCWyPudciYd6ited
```

**Comment by mdp** [comment]
This most likely has to do with the way they are doing the PBKDF on the latest version of Openssl, now defaulting to SHA256 vs MD5.

Unfortunately, OpenSSL hasn't aged well and my suggestion would be to find a more secure method to send data. The problem with OpenSSL's command line encryption is that the AES mode is weak, the PBKDF is iterated only once, and it's not authenticated (Someone in the middle can corrupt the data without your knowing).

That being said, I don't know of a good replacement for OpenSSL as a command line client. GPG is really the only CLI out there with reasonable security, but obviously not great UX for the client. Libsodium is what I would default to, but they don't provide any command line tools, as it's just a library.

As for fixing this problem, I'd take a look at generating the key with the `pkcs5_keyivgen`

http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html#method-i-pkcs5_keyivgen

Something along the lines of `pcks5_keyivgen(pass, salt, 1, OpenSSL::Digest::SHA256)` and see if that works.

Sorry, this is still a bit of an unsolved problem.
