### ISSUE TITLE
Add unified exceptions

### ISSUE THREAD

**Issue by rsim** [mdp/gibberish#3]
I was experimenting with Gibberish::AES and it really provides nice encryption/decryption API. But if I want to catch exceptions in my application when Gibberish::AES#decrypt cannot decrypt provided argument then it is not easy.

Gibberish::AES#decrypt with nil argument raises "NoMethodError: undefined method `unpack' for nil:NilClass", with empty string argument raises "TypeError: can't convert nil into String", with wrong decryption key raises "OpenSSL::Cipher::CipherError: Given final block not properly padded". As a result I need to catch any exception in my application and assume that it was caused by decrypt.

It would be better if Gibberish::AES#decrypt would always raise something like Gibberish::DecryptionError with more details in error message and then it would be easier for applications to catch just this exception.

**Comment by jborrey** [comment]
This should solve: https://github.com/mdp/gibberish/pull/25
